export const FETCH_SHOWS_REQUEST = 'FETCH_SHOWS_REQUEST'
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS'
export const FETCH_SHOWS_FAILURE = 'FETCH_SHOWS_FAILURE'
export const FILTER_SHOWS = 'FILTER_SHOWS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const SET_STRIPE_CHECKOUT = 'SET_STRIPE_CHECKOUT'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_RESET = 'LOGIN_RESET'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP'

export const SET_BILLING_OPTIONS = 'SET_BILLING_OPTIONS'
export const CLEAR_BILLING_OPTIONS = 'CLEAR_BILLING_OPTIONS'

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE'

export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE'

export const LIVESHOW_REQUEST = 'LIVESHOW_REQUEST'
export const LIVESHOW_SUCCESS = 'LIVESHOW_SUCCESS'
export const LIVESHOW_FAILURE = 'LIVESHOW_FAILURE'
export const LIVESHOW_CLEAR = 'LIVESHOW_CLEAR'

export const SET_SHOW = 'SET_SHOW'
export const SET_PANEL_COMPONENT = 'SET_PANEL_COMPONENT'